### ISSUE TITLE
Message format requires double stringify / parse

### ISSUE THREAD

**Issue by ghost** [openflint/flint-player#1]
Messages sent to the player require the `payload` subproperty _and_ the resulting message to be run through `JSON.stringify` and similarly messages received require `JSON.parse` twice as well - is there a technical reason for this?

**Comment by ghost** [comment]
Actually, it seems that this behavior originates in [`mediaplayer.js`](https://github.com/openflint/flint-receiver-sdk/blob/gh-pages/v1/libs/mediaplayer.js) in the [flint-receiver-sdk](https://github.com/openflint/flint-receiver-sdk) project, not in this project.

**Comment by jsli** [comment]
Ok, let me explain this.
1. A sender can only send text message to receiver, so a structured message must do 'stringify' before sending. That is the first 'stringify'.
2. The message will be packaged by sdk like this:

```
{
    "namespace":"urn:flint:org.openflint.fling.media",
    "payload":"some message"
}
```

The real message is in `payload` sub-property. And the packaged message also need to do 'stringify' before sending to Flint Service(it's a message forwarding center). That is the second 'stringify'.
1. When the receiver side received the message, the receiver sdk parse the message as a JSON object.
   That's the first 'parse'. And the receiver sdk strip the outer-properties, 'namespace' and 'payload'. Then the receiver sdk will send the value of `payload` to a message bus named the same as the value of 'namespace'.
2. When the message bus received `payload', it should do 'parse' to get the structured message. That's the second 'parse'.

**Comment by jsli** [comment]
BTW, a new sdk is under developing.
Please refer to: `https://github.com/openflint/flint-web-sdk`

**Comment by ghost** [comment]
Sounds like this behaves as expected if `payload` must be a string - closing!
